chore: refer-to-common-ErrorInfo-schema
camaraproject/QualityOnDemand pull request #126
Opened 2023-03-03 12:23 UTC by jlurien

As agreed in the discussion in Commonalities (https://github.com/camaraproject/WorkingGroups/issues/151), we should adopt the new agreement to refer to the common ErrorInfo schema for every error.

2023-03-03 16:53 UTC, hdamker requested changes
There are reference to previous error schemas in two lines: 

- 57: `$ref: "#/components/schemas/Error400" `
- 110: `$ref: "#/components/schemas/Error409"`

which need to be replaced.

Rest looks good to me.

2023-03-06 09:51 UTC, jlurien commented
> There are references left to previous error schemas in two lines:
> 
> * 57: `$ref: "#/components/schemas/Error400" `
> * 110: `$ref: "#/components/schemas/Error409"`
> 
> which need to be replaced.
> 
> Rest looks good to me.

Indeed. I missed the inline ones. Corrected. Thanks

2023-03-06 19:22 UTC, hdamker approved these changes
LGTM now

2023-03-06 19:38 UTC, shilpa-padgaonkar approved these changes

2023-03-07 06:49 UTC, merged