Fix/meeting minutes reference
camaraproject/QualityOnDemand pull request #308
Opened 2024-06-21 11:24 UTC by maxl2287

#### What type of PR is this?

* subproject management

#### What this PR does / why we need it:
Fixes the meeting-minute link to confluence.

#### Which issue(s) this PR fixes:

Fixes #307

2024-06-21 12:14 UTC, hdamker requested changes
Thanks for the PR, good catch ... see just my proposal regarding the link (created with "Share", making it independent of name changes).

2024-06-21 12:14 UTC, hdamker commented on README.md
> +* Schedule: bi-weekly, Friday, 2 PM CET/CEST (13:00 UTC, 12:00 UTC during European DST). For date/time of the next meeting, see previous [meeting minutes](https://wiki.camaraproject.org/display/CAM/Q
```suggestion
* Schedule: bi-weekly, Friday, 2 PM CET/CEST (13:00 UTC, 12:00 UTC during European DST). For date/time of the next meeting, see previous [meeting minutes](https://wiki.camaraproject.org/x/0AOeAQ).
```

2024-06-21 12:20 UTC, hdamker commented
@maxl2287 Found another link which needed correction, done in https://github.com/camaraproject/QualityOnDemand/pull/308/commits/2a17108bdb98f90dd8c99bb2309890b98d7cecf8

2024-06-24 20:40 UTC, RandyLevensalor approved these changes
Thanks for updating the links and the additional cleanup.

2024-06-25 06:16 UTC, merged