Align on Commonalities' subscription-model by using `sink` and `sinkCredentials`
camaraproject/QualityOnDemand pull request #335
Opened 2024-08-05 09:59 UTC by maxl2287

#### What type of PR is this?

Add one of the following kinds:

* enhancement/feature

#### What this PR does / why we need it:
Aligns on Commonalities' updated subscription model.

#### Which issue(s) this PR fixes:
Fixes #332

2024-08-05 11:15 UTC, hdamker requested changes
sinkCredentials are currently within the Design Guidelines quite restricted. Added here to the descriptions.

2024-08-05 11:15 UTC, hdamker commented on code/API_definitions/quality-on-demand.yaml
> +          description: "The type of the credential."
Commonalities 0.4.0 says in the Design Guidelines explicit: "Type of the credential - MUST be set to ACCESSTOKEN for now". So we should mentioned it also here:

```suggestion
          description: "The type of the credential. With the current API version the type MUST be set to `ACCESSTOKEN`"
```

2024-08-05 11:15 UTC, hdamker commented on code/API_definitions/quality-on-demand.yaml
> +              description: REQUIRED. Type of the access token (See [OAuth 2.0](https://tools.ietf.org/html/rfc6749#section-7.1)).
```suggestion
              description: REQUIRED. Type of the access token (See [OAuth 2.0](https://tools.ietf.org/html/rfc6749#section-7.1)). For the current version of the API the type MUST be set to `Bearer`.
```

2024-08-05 11:15 UTC, hdamker commented on code/API_definitions/quality-on-demand.yaml
> +    Additionally, sink credentials may be provided to authenticate and authorize the delivery of events to the sink.
```suggestion
    Additionally, sink credentials may be provided to authenticate and authorize the delivery of events to the sink. In order to be updated in future this object is polymorphic. See detail below. It is RECOMMENDED for subscription consumer to provide credential to protect notification endpoint.
```

2024-08-05 12:35 UTC, jlurien reviewed
You have to correct as well:       bearerFormat: "{$request.body#/webhook/notificationAuthToken}" -> bearerFormat: "{$request.body#/sinkCredential.credentialType}"

2024-08-05 12:36 UTC, jlurien commented
> sinkCredentials are currently within the Design Guidelines quite restricted. Added here to the descriptions.

In QoD Provisioning I have adjusted the previous text to:

```
    * **Notification URL and token**:
    Developers may provide a callback URL (`sink`) on which notifications about all status change events (eg. provisioning termination) can be received from the service provider. This is an optional parameter. The notification will be sent as a CloudEvent compliant message. If `sink` is included, it is RECOMMENDED for the client to provide as well the `sinkCredential` property to protect the notification enpoint. In the current version,`sinkCredential.credentialType` MUST be set to `ACCESSTOKEN` if provided.
```

cc @maxl2287

2024-08-05 13:01 UTC, jlurien reviewed
I have added also 410 as response to       
     callbacks:
        notifications:
          "{$request.body#/sink}":

As in the artifact because it has an explict reference to notifications:

    Generic410:
      description: Gone
      headers:
        x-correlator:
          $ref: "#/components/headers/x-correlator"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorInfo"
          examples:
            GENERIC_410_GONE:
              description: Use in notifications flow to allow API Consumer to indicate that its callback is no longer available
              value:
                status: 410
                code: GONE
                message: Access to the target resource is no longer available.

2024-08-05 15:57 UTC, hdamker commented on code/API_definitions/quality-on-demand.yaml
> +    Developers may provide a callback URL (`sink`) on which notifications about all status change events (eg. provisioning termination) can be received from the service provider. This is an optional
```suggestion
    Developers may provide a callback URL (`sink`) on which notifications about all status change events (eg. provisioning termination) can be received from the service provider. This is an optional parameter. The notification will be sent as a CloudEvent compliant message.
```

2024-08-05 16:16 UTC, hdamker commented
> @hdamker shell I also update the BadRequest with the error-examples?

@maxl2287 the current Generic400 "BadRequest" is a copy from line 131ff of [Commonalities/blob/main/artifacts/CAMARA_common.yaml](https://github.com/camaraproject/Commonalities/blob/main/artifacts/CAMARA_common.yaml) and fits for the other endpoints.

INVALID_CREDENTIAL and INVALID_TOKEN are specific for createSession only - so I suppose you have to introduce and additional `CreateSessionBadRequest400` similar as in the [event-subscription-template](https://github.com/camaraproject/Commonalities/blob/9233f834c9cfb44dbb843ca72f22085f8559d4da/artifacts/camara-cloudevents/event-subscription-template.yaml#L799)? 

@jlurien also relevant for #299

2024-08-06 07:36 UTC, jlurien approved these changes

2024-08-06 08:58 UTC, hdamker commented on code/API_definitions/quality-on-demand.yaml
> +    GenericExtendSessionDuration400 :
```suggestion
    GenericExtendSessionDuration400:
```

2024-08-06 09:00 UTC, hdamker approved these changes

2024-08-07 11:16 UTC, merged