Patch release r1.3
camaraproject/QualityOnDemand pull request #383
Opened 2024-12-10 09:37 UTC by hdamker

#### What type of PR is this?

* subproject management
* documentation

#### What this PR does / why we need it:

Update of README and changelog for patch release r1.3
Updating release numbers and API versions across all files
Replacing links to main branch with release specific links (closing the remaining issue from the patch release scope in #

#### Which issue(s) this PR fixes:

Fixes #381 
Fixes #363

#### Special notes for reviewers:

Create temporarily created branch `r1.3` from main to be able to test the links. That branch will need be deleted before the release tag can be created.

#### Changelog input

```
na

```

2024-12-17 16:27 UTC, eric-murray submitted a review, later dismissed

2024-12-17 16:37 UTC, RandyLevensalor requested changes
@hdamker Can you please update documentation/API_documentation/qos-profiles-API-Readiness-Checklist.md to include that we now have a user story?

2024-12-17 16:51 UTC, jlurien submitted a review, later dismissed
LGTM with minor suggestions

2024-12-17 16:51 UTC, jlurien commented on CHANGELOG.md
> +Note: this release is a patch release, containing some clarifications and updates within the documentation. The API versions are fully backward-compatible to the ones in r1.2. Please see there for th
```suggestion
Note: this release is a patch release, containing some clarifications and updates within the documentation. The API versions are fully backward-compatible to the ones in r1.2. Please see there for the main changes compared to previous 0.10.x release.
```

2024-12-17 16:51 UTC, jlurien commented on CHANGELOG.md
> +* Documented that the error response QUALITY_ON_DEMAND.DURATION_OUT_OF_RANGE can't be returned for /extend and will be removed within next version by @hdamker in https://github.com/camaraproject/Qual
```suggestion
* Documented that the error response QUALITY_ON_DEMAND.DURATION_OUT_OF_RANGE cannot be returned for /extend and will be removed within next version by @hdamker in https://github.com/camaraproject/QualityOnDemand/pull/382
```

2024-12-17 16:51 UTC, jlurien commented on README.md
> +* **The latest public release is [r1.3](https://github.com/camaraproject/QualityOnDemand/tree/r1.3) a patch release of r1.2 with the following API definitions:**
```suggestion
* **The latest public release is [r1.3](https://github.com/camaraproject/QualityOnDemand/tree/r1.3), a patch release of r1.2, with the following API definitions:**
```

2024-12-17 17:12 UTC, hdamker commented
> @hdamker Can you please update documentation/API_documentation/qos-profiles-API-Readiness-Checklist.md to include that we now have a user story?

@RandyLevensalor Sure ... done in 2b223a8c0f83852cdb6edbdeb2e75b4cf77a4866

2024-12-17 17:13 UTC, hdamker commented
> LGTM with minor suggestions

@jlurien Thanks for the review, all suggestions committed.

2024-12-17 17:32 UTC, RandyLevensalor approved these changes

2024-12-17 20:55 UTC, eric-murray approved these changes

2024-12-18 08:27 UTC, jlurien approved these changes

2024-12-18 14:30 UTC, tanjadegroot approved these changes

2024-12-18 14:31 UTC, tanjadegroot commented
Hi Herbert, sorry for the delay. I reviewed and have some comments, but you may decide to apply them in the next release.

OK to go from release management team

2024-12-18 14:56 UTC, hdamker commented
> Hi Herbert, sorry for the delay. I reviewed and have some comments, but you may decide to apply them in the next release.

Hi Tanja, thanks for the comments. I created a new issue to consider them within the next release, they are going beyond the scope of a release PR.

2024-12-18 14:56 UTC, merged